# Identity Setting
# ================
# you should change this to suit your own preference.

title:       neizod's speculation
description: insufficient data for meaningful answer
logo:        "/assets/img/logo.png"
cover:       "/assets/img/cover.png"

baseurl:     ""
url:         "https://neizod.github.io"

owner:  neizod
rights: CC-BY

# Social & Sharing
# ----------------

google:
  analytics:    UA-2498230-6
  verification: R28DTjp2yjUO-i7K4fdLkSGd-e99QNiewcyJeOjEi6E

facebook:
  username: neizod
  app_id:   772191139548544

twitter:
  username:          neizod
  widgets:           true
  share_large_image: false

disqus:
  username: neizod


# Content Setting
# ===============
# you may change this to suit your own preference.

timezone: Asia/Bangkok
paginate: 10
mathjax:  true


# Engine Setting
# ==============
# you shouldn't change this unless you really know what you're doing.

paginate_path: "/posts/page:num"

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      article: true
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: project

sass:
  sass_dir: "_sass/"
  style: compressed

exclude:
  - README.md
  - LICENSE.txt

gems:
  - jekyll-sitemap
  - jekyll-paginate

empty_array: []
